"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const usercontroller_1 = require("../controllers/usercontroller");
const router = (0, express_1.Router)();
router.get('/', usercontroller_1.getallusers);
router.get('/:id', usercontroller_1.getuserbyid);
router.put('/:id', usercontroller_1.updateuser);
router.delete('/:id', usercontroller_1.deleteuser);
exports.default = router;
